version: "3"

networks: 
  jsnet:

services:
  app:
    env_file: ./.env
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/usr/app
    ports:
      - "${APP_PORT}:3000"
    networks:
      - jsnet
    depends_on:
      - mongo
  
  mongo:
    env_file: ./.env
    container_name: mongo
    image: 'mongo'
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - jsnet