version: '3.7'

services:
  app:
    env_file: ./.env
    container_name: "${APP_CONTAINER_NAME}"
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./app:/usr/app
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on: 
      - mongo

  mongo:
    env_file: ./.env
    image: "mongo:${MONGO_IMAGE_VERSION}"
    container_name: "${MONGO_CONTAINER_NAME}"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db:/data/db

  mongo-express:
    env_file: ./.env
    image: mongo-express
    container_name: "${ME_CONTAINER_NAME}"
    restart: always
    ports:
      - "${ME_PORT}:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_PASSWORD}"
      ME_CONFIG_MONGODB_PORT: "${MONGO_PORT}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASSWORD}"

  